### ISSUE TITLE
font awesome 5.0

### ISSUE THREAD

**Issue by nteetor** [ThinkRstat/fa#4]
Hello hello, I am working on a new iteration of shiny, see [dull](https://github.com/nteetor/dull). As part of that project, I was going to put together an "fa" package to support working with new Font Awesome 5 features. However, I suspected someone might already have a similar project underway. My search brought me to this repo. If I may ask,

1. Is this project still under development? Was the project going to be put on CRAN?
1. If so, could I help get this package supporting FA 5 and out to CRAN?  
1. If not, could I use the name "fa"?

Thank you, Nate

**Comment by nteetor** [comment]
* after a second read through it looks like this package would support FA icons on the desktop whereas I hoped to build a toolset for FA on the web. I don't see that preventing collaboration, but our imagined toolsets may be more different than I first thought. I am hoping to support the SVG features and transforms found here https://fontawesome.com/how-to-use/svg-with-js.

**Comment by romainfrancois** [comment]
This is not really under development. You might want to look at https://github.com/ropenscilabs/icon
